doc/source/api/force_wfmanager.left_side_pane.rst
force_wfmanager/left_side_pane/mco_model_view.py
force_wfmanager/left_side_pane/new_entity_modal.py
force_wfmanager/left_side_pane/workflow_model_view.py
force_wfmanager/left_side_pane/workflow_settings.py
force_wfmanager/wfmanager_plugin.py
force_wfmanager/wfmanager_task.py
test/test_new_entity_modal.py
test/test_workflow_settings.py

Adds support for MCO parameters in the UI. MCO parameters are added under the MCO in the model.
Currently, the parameters are not specific to the MCO, but it's likely they will become.

Add MCO parameter support in the GUI

---

force_wfmanager/left_side_pane/workflow_settings.py

The `selected_mco` attribute is not used anymore, it was an attribute representing the currently selected mco in the list of mco bundles. This list of mco bundles is now an attribute of the modal dialog, not the workflow settings class.

Remove trailing attribute for the workflow settings

---

force_wfmanager/left_side_pane/new_entity_modal.py
force_wfmanager/left_side_pane/workflow_settings.py
force_wfmanager/wfmanager_task.py
test/test_new_entity_modal.py
test/test_wfmanager_task.py
test/test_workflow_settings.py

Rename Workflow variables so that it is easier to understand which is the workflow model view object and the workflow model object (`workflow_mv` and `workflow_m`)
I also made the workflow model view private inside the `WorkflowSettings` class

Rename Workflow variables

---

force_wfmanager/central_pane/analysis.py
force_wfmanager/central_pane/result_table.py
test/test_analysis.py
test/test_result_table.py

Adds a result table in the main UI pane. This table will display the results obtained by the evaluation. Columns will be titled over the input parameter values and KPI obtained. Rows will be the individual evaluations.

Add result table

---

force_wfmanager/left_side_pane/view_utils.py
force_wfmanager/left_side_pane/workflow_settings.py
test/test_mco_model_view.py
test/test_workflow_settings.py

Introduce base views for each element of the Workflow (MCO parameter, Data source, KPI calculator). Those base views are displayed when clicking on the specific element in the tree. 
The user can now edit those element by right clicking on the element in the tree, and click "Edit".

Introduce base views

---

force_wfmanager/wfmanager_task.py
test/test_wfmanager_task.py

We now keep in memory which file is currently edited, so that the application doesn't open a new dialog every time the user clicks on save

Add current_file attribute

---

force_wfmanager/left_side_pane/workflow_settings.py

On MacOS it is not possible to retrieve the dock pane once it is closed, so we just remove the possibility of closing the pane.

Remove possibility of closing the pane

---

force_wfmanager/tests/test_wfmanager_task.py
force_wfmanager/wfmanager_task.py

Fixes #74 
The application has now "Save" and "Save as..." actions. The save action is disabled by default, and enabled only if a Workflow has already been loaded from a file, or the save as action has already been processed. The save as action can always be triggered, and will change the current file on which the application is currently writing.

Add Save as... action to the application

---

force_wfmanager/central_pane/central_pane.py
force_wfmanager/central_pane/tests/test_central_pane.py
force_wfmanager/tests/test_wfmanager_task.py
force_wfmanager/wfmanager_task.py

It is convenient that the model is outside the UI element and into the Task, for later manipulation

Move Analysis model outside the central pane and into the Task

---

force_wfmanager/central_pane/central_pane.py
force_wfmanager/central_pane/plot.py
force_wfmanager/central_pane/result_table.py
force_wfmanager/central_pane/tests/test_plot.py
force_wfmanager/central_pane/tests/test_result_table.py

Fixes #92 
Add binding between the selected point in the plot and the selected row in the table. I also changed the layout of the central pane, the table is now next to the plot instead of in a separate tab.

Add evaluation step selection binding between table and plot

---

force_wfmanager/left_side_pane/evaluator_model_view.py

When creating a slot row, given a name for the slot, it triggers the `name` listener before the instance is properly created. 
```
ERROR:traits:Exception occurred in traits notification handler for object: <force_wfmanager.left_side_pane.evaluator_model_view.OutputSlotRow object at 0x1257e0d00>, trait: name, old value: , new value: ptot
Traceback (most recent call last):
File "/Users/sborini/.edm/envs/force35/lib/python3.5/site-packages/traits/trait_notifiers.py", line 519, in _dispatch_change_event
self.dispatch( handler, *args )
File "/Users/sborini/.edm/envs/force35/lib/python3.5/site-packages/traits/trait_notifiers.py", line 482, in dispatch
handler( *args )
File "/Users/sborini/Work/github/force-h2020/force-wfmanager/force_wfmanager/left_side_pane/evaluator_model_view.py", line 43, …
```

Fix the issue with the table row initialization

---

force_wfmanager/server/tests/test_zmq_server.py
force_wfmanager/server/zmq_server.py
force_wfmanager/tests/utils.py

We were dropping the last point because the final pub and the sync goodbye
came at the same time, and the sync was examined first, leading to a state change
and thus to dropped data.

Do not drop last point by inverting the socket check order.

---

force_wfmanager/tests/test_wfmanager_task.py
force_wfmanager/wfmanager_task.py

Prevents accidental deletion of the current non-empty table when clicking "run" on a new calculation, asking for confirmation.

Add confirmation dialog when clicking on the "Run" button

---

force_wfmanager/left_side_pane/evaluator_model_view.py
force_wfmanager/left_side_pane/tests/test_evaluator_model_view.py

Synchronize the models with the slot tables.
This PR is a workaround for the issue #58, it doesn't fix the issue at all. But at least now the table shows to the user the correct current name of the slots.
This doesn't ensure that the type of the slot is synchronized with the model, but as "slots" method is not part of the model, we cannot know if the type changed.

Synchronize the slot tables with the model

---

force_wfmanager/left_side_pane/workflow_settings.py

This is a workaround for the issue #58. The UI now behave properly, and the model is correctly synchronized with the table view.
But it removes the possibility to discard the changes on the model by clicking on "Cancel"

Use a livemodal dialog when editing the model

---

force_wfmanager/wfmanager_task.py

Addresses issue #126, the table and plot should now be cleared even if a calculation does not complete successfully.

Clear table before starting evaluation

---

force_wfmanager/left_side_pane/kpi_specification_model_view.py
force_wfmanager/left_side_pane/tests/test_kpi_specification_model_view.py
force_wfmanager/left_side_pane/tests/test_mco_model_view.py

Made kpi model track the name of the associated modelviewer. This prevents an error where nameless kpis would not be returned as output.
Also some slight changes to the MCO model viewer tests, as we now assign a name to the kpi model on initialisation. In a real run of the program this is passed as an argument to the kpi modelviewer, so the test was updated to reflect that.
This pr doesn't yet address the saving/loading behaviour, but I'd like to get it merged anyway as you can't run a computation in the workflow manager without this fix.

163 kpi name saves - partial

---

force_wfmanager/left_side_pane/data_source_model_view.py

When creating a workflow from a json file, the program uses this file to create the model - which should then automatically update the workflow model view. 
However with datasource names there was an issue where the Input row in the model view could not be assigned a name without first being assigned a list of available (name) variables. This then called functions designed to a) enusure the name was in available names  and b) enforce consistency between the modelview and model. The program essentially acted as if a user had selected the default name from the ui.
The fix was just to check a) elsewhere, in a way which did not trigger b) immediately.
Sorry for the long description, but it's such a small fix for a complicated (at least for me!) problem I felt it made sense to give some …

163 fixed names not loading for datasources

---

force_wfmanager/left_side_pane/tests/test_kpi_specification_model_view.py
force_wfmanager/left_side_pane/tests/test_workflow_model_view.py
force_wfmanager/left_side_pane/workflow_model_view.py
force_wfmanager/wfmanager_task.py

Originally, deleting a datasource called a unwritten function in workflow_model_view. There is also an extra test for a named KPI, as we were only checking the default one before.
The KPI issue comes from the merge with master, but since this is such a small commit the single line of code not checked was causing the coverage checks to fail!

Deletable data sources and extra KPI specification test

---

force_wfmanager/wfmanager_task.py

Addresses #75. This workaround removes the task from the window before calling the usual close method(s) - since there are now no UItems to require a sizehint() the exception is no longer raised.

Workaround for exceptions on closing wfmanager

---

force_wfmanager/left_side_pane/kpi_specification_model_view.py
force_wfmanager/left_side_pane/tests/test_kpi_specification_model_view.py

Addreses #196. Fixes an error where kpi_mv.name would never actually be set, and checks for kpi_mv.model.name being set to ''. This could happen automatically if the thing model.name was already set to was removed from the list of available variables. This would set kpi_mv.model.name = ''.
However, properties which depended on model.name did not seem to track this change.

KPI Label not being unset

---

force_wfmanager/wfmanager_task.py

enabled got changed to ui_enabled in side pane, but this was not done in wfmanager_task

Run button fix

---

force_wfmanager/left_side_pane/tests/test_workflow_tree.py
force_wfmanager/left_side_pane/workflow_model_view.py

Addresses https://github.com/force-h2020/force-wfmanager/issues/187. The change in the pr makes it so we now only create a modelview for models whose factory has ui_visible set to True. This is the default case in base_notification_listener_factory.

Hide ui notification

---

force_wfmanager/left_side_pane/new_entity_modal.py
force_wfmanager/left_side_pane/tests/test_new_entity_modal.py
force_wfmanager/tests/test_wfmanager_task.py
force_wfmanager/wfmanager_task.py

Fixes #218 #216. Uses the actual names for plugins instead of id, though still uses id if a plugin does not have a name assigned. Plugins listed in alphabetical order.

Use Plugin Names

---

force_wfmanager/wfmanager.py

Prevents raising exceptions on closing by removing the tasks from the window prior to closedown. This is the same workaround as for the menu bar closedown, except it requires implementing something for the application_exiting event in TasksApplication.
Not really sure how to write a test for this as it requires a window with tasks within the test environment!

Title bar close bugfix

---

force_wfmanager/left_side_pane/new_entity_modal.py
force_wfmanager/left_side_pane/tests/test_new_entity_modal.py

A few small changes: Added Unicode, consistently used " over ' for strings, more sensible variable names and HTML strings are now created using a function rather than using .format within a function.

Refactor new_modal_dialog

---

force_wfmanager/wfmanager.py
force_wfmanager/wfmanager_task.py

The previous fix #226 was causing the tasks to be deleted in _application_exiting_fired, before saving the application state. This happens in tasks_application.py:
def _prepare_exit(self):
""" Called immediately before the extant windows are destroyed and the GUI event loop is terminated."""
self.application_exiting = self
self._save_state()
The fix is just to override _prepare_exit in wfmanager.py and switch the order of these two calls. The application_exiting event does not appear to be used anywhere else (searching the files in site-packages for "application_exiting" gives no results)

Close Exceptions MkII

---

force_wfmanager/central_pane/plot.py
force_wfmanager/central_pane/tests/test_plot.py

Addresses #184, #185 & #186. While the plot did seem to get resized automatically, it sets the plot boundary to be exactly on an outlying plot point. This adds a little space around these edge values (10% of the plot height/width) and provides a button to reset the plot view. 
This also resets the plot view when there are no data value names available (and therefore no data to plot), for example after the analysis model has been cleared.

Plot Display Resizing

---

force_wfmanager/tests/test_wfmanager.py
force_wfmanager/tests/test_wfmanager_task.py
force_wfmanager/wfmanager.py
force_wfmanager/wfmanager_task.py

This creates a subclass of TaskWindow which has an exit prompt, which gives the user a chance to save before quitting. 
Putting this functionality in the TaskWindow's close() method means it will also be triggered on closing via title bar, not just those performed through the menu bar. 
It currently relies on the first task in window.tasks being the WfManagerTask, as well as the window being the only TaskWindow (so closing it means exiting the application).

Exit method moved to TaskWindow subclass

---

force_wfmanager/plugins/ui_notification/event_serializer.py
force_wfmanager/plugins/ui_notification/tests/test_event_serializer.py
force_wfmanager/plugins/ui_notification/tests/test_ui_notification.py
force_wfmanager/plugins/ui_notification/ui_notification.py
force_wfmanager/server/event_deserializer.py
force_wfmanager/server/tests/test_event_deserializer.py
force_wfmanager/tests/test_wfmanager_task.py
force_wfmanager/wfmanager_task.py

After PR 187 in force-bdss, this PR syncs the wfmanager plugin against the changes in MCOProgressEvent and MCO.

Sync against change in MCOProgressEvent and design change in MCO

---

force_wfmanager/left_side_pane/data_source_model_view.py
force_wfmanager/left_side_pane/workflow_tree.py

Fixes #217. Due to resizing issues with HTMLEditor, it may be easier to use the basic HTML parsing offered by TextEditor. This only needs to be done for regions where there is not enough space for all the Items to be displayed at their full extent.

Remove HTML from main window

---

CHANGES.rst
force_wfmanager/gui/run.py
force_wfmanager/gui/tests/test_click_run.py

Adds a cmd line option --debug which adds debug logs to force_wfmanager.log.
The only test is a run with debug=True passed to main. I'm not even sure if it should have this, since the logger is a system-wide thing, so any subsequent tests will also have debug logs written to force_wfmanager.log.
This doesn't cause any problems at the minute, but does mean the tests aren't totally self-contained.

Debug Logging Option

---

ci/__main__.py
force_wfmanager/central_pane/analysis_model.py
force_wfmanager/central_pane/plot.py
force_wfmanager/central_pane/result_table.py
force_wfmanager/central_pane/tests/test_analysis_model.py
force_wfmanager/central_pane/tests/test_graph_pane.py
force_wfmanager/central_pane/tests/test_plot.py
force_wfmanager/central_pane/tests/test_result_table.py
force_wfmanager/gui/run.py
force_wfmanager/gui/tests/test_click_run.py
force_wfmanager/left_side_pane/tests/test_result_pane.py
force_wfmanager/left_side_pane/workflow_info.py
force_wfmanager/local_traits.py
force_wfmanager/tests/test_run.py
force_wfmanager/tests/test_wfmanager.py
force_wfmanager/tests/test_wfmanager_tasks.py

This PR fixes #254 by switching the results view from TableEditor to a TabularEditor. This had a few side effects, as listed below:
- A fix to TraitsUI was required enthought/traitsui#521 which has since been merged to master, and thus this PR pins the TraitsUI version required by this package to that particular commit, to be switched back in the future (see #258)
- By switching to TabularEditor, you can now select multiples rows or multiple points on the plot to be highlighted.
- The plotting style was modified slightly to accommodate multiple selections.
- One other minor change is that the Force logo now rescales depending on the window size, rather than enforcing a minimum width ~500 pixels.
- Added --profile flag to force_wfmanager entrypoint that provides .prof/.pstats files.

Improved ResultsPane performance with TabularEditor and enabled multi-point selections

---

force_wfmanager/central_pane/plot.py
force_wfmanager/central_pane/tests/test_plot.py

Adds option to colour points by a third column in results pane, with choice of continuous/discrete colourmaps.
Current issues:
- ~GUI displays cmaps selection as `<function $name #memaddr>`, rather than just the name.~
- solved
- ~When switching colourmaps, the plot axes reset (losing e.g. any existing zoom/pan).~
- solved
- ~Discrete colourmaps cause a crash when used with e.g. floating point data.~
- disabled discrete colormaps for now

Added colour mapped scatter plots

---

force_wfmanager/left_side_pane/data_source_model_view.py
force_wfmanager/left_side_pane/new_entity_creator.py
force_wfmanager/left_side_pane/workflow_info.py
force_wfmanager/left_side_pane/workflow_tree.py
force_wfmanager/plugin_dialog.py

Some minor fixes to the wfmanager interface.
- Changes HTML font to sans-serif to match the rest of the GUI.
- Use trait `label` rather than `name` in model descriptions if defined.
- Fixes #261 by making plugin list uneditable.

Minor interface fixes

---

force_wfmanager/central_pane/analysis_model.py
force_wfmanager/central_pane/tests/test_analysis_model.py
force_wfmanager/tests/test_wfmanager.py
force_wfmanager/tests/test_wfmanager_tasks.py
force_wfmanager/wfmanager_results_task.py

Closes #266 .
This PR adds the following functionality to the workflow manager and its GUI:
- Export analysis model (i.e. table of results) to JSON or CSV, for use elsewhere.
- Save "Project" files containing the analysis model *and* the workflow used to generate it.
- This required a change to the results task such that it takes a copy of the workflow when it has been run, and does not update with the setup task's copy.
- Open project files from the results view, loading the correct state into both results and setup task, displaying the results in the default view.

Save and load results alongside the workflow that created them

---

force_wfmanager/left_side_pane/tests/test_workflow_tree.py
force_wfmanager/left_side_pane/workflow_tree.py

PR https://github.com/force-h2020/force-bdss/pull/205 moved verification checks to the class being verified, rather than doing everything at the Workflow level. This was supported by the UI for everything except errors in `InputSlotInfo` and `OutputSlotInfo`, as the error occurs in these classes but is displayed at the `DataSource` level.

Updated how errors are displayed in the UI against changes in the BDSS

---

ci/__main__.py

Dependency on 3rd party `mock` was removed in https://github.com/force-h2020/force-bdss/pull/219
However, `pyface==6.0.0-2` `GuiTestAssistant` class still imports it explicitly, which is used in several test wfmanager test functions.
In future it would be great to use `pyface>=6.1.0`, which includes replacing `mock` with `unittest.mock`, though this also requires unpinning other libraries (`traitsui`, `chaco` etc...)
For now, `mock==2.0.0-1` is put back in as a dependency to the wf_manager `ci.__main__.py`

BUG: included mock in dependencies for GuiTestAssistant in pyface

---

ci/__main__.py
setup.py

There was an error in `setup.py` where `package_data` was given as a string rather than a list of strings. This was fine on unix but I guess on windows it tries to do some path conversion and fails there.
Also upgraded numpy & chaco since we need them for plugins using scipy (which is most of them!)

Fixes for windows build

---

.travis.yml

XVFB now not called directly on Travis CI for versions of Ubuntu >= 16.04 (Xenial), but instead introduced using `services`
https://slack-redir.net/link?url=https%3A%2F%2Fdocs.travis-ci.com%2Fuser%2Fgui-and-headless-browsers%2F
Workaround includes also explicitly installing `libglu` drivers to ensure that all test involving `qt` run.
Also set testing version of Ubuntu as Bionic, as this will be the system aimed for release.

Fix: updated .travis.yml for XVFB handing on Ubuntu >= Xenial

---

force_wfmanager/tests/test_wfmanager.py

Simple fix in a test.
Note: `current_file` is a File() trait.
With this addition, I have the whole test suite passing locally on Windows.
(The CI failure seems unrelated and affects all commits to master at the moment)

Fix: test filename in OS-independent way

---

.travis.yml

This PR:
- adds a macOS CI job
- makes other updates to CI VM (`generic` instead of `c`, no `ccache`) and edm setup (newest edm, Python 3.6 for bootstrap).
Similar to https://github.com/force-h2020/force-bdss/pull/223

Travis ci macos

---

force_wfmanager/ui/review/plot.py

Minor bug fix to `Plot` object to address https://github.com/force-h2020/force-wfmanager/issues/292
Deprecated warnings still showing in tests come from `chaco==4.7.2-3` and `pyface==6.0.0-2` packages.

BUG: changed deprecated HasTraits.set method to HasTraits.traits_set

---

force_wfmanager/ui/tests/test_ui_utils.py

Fixes #315 
The test was designed in order to check different breakpoints based on the length of str(class), so it's essential that str(class) returns the full path starting from the repository root.
If the test is run from a subdirectory, I just change `__module__` in place to its full form.

Make TestUiUtils.test_class_description pass from subdirectories

---

force_wfmanager/ui/review/plot.py
force_wfmanager/ui/review/tests/test_plot.py

This PR
- reworks the listeners' logic in `BasePlot`, to close #318, and to remove the `timer.Stop()` call that wasn't working. Now the changes of axes triggers a recenter; the plot ranges are updated based on the timer but only if there were changes in the `evaluation_steps`
- allows switching from colormapped to non-colormapped and back, without losing the pan & zoom

Handling of plot updates and resizes

---

force_wfmanager/ui/setup/mco/kpi_specification_view.py

In #313 the variables that were able to be selected in the UI as KPIs were restricted to output variables that were not consumed during the workflow. Therefore they could not also appear as input variables.
This was intended to simplify the UI, considering that most use case KPIs tended to be output variables produced at the end of the workflow process. However, it also restricts the possibility of optimising an intermediate variable as a KPI, which also has valid possible use cases, including the `enthought-example` plugin. 
This PR includes a simple fix to allow the user to choose between all output variables generated by `DataSource`s as possible KPIs.

Bug fix to KPI name options

---

.travis.yml
force_wfmanager/gui/run.py
force_wfmanager/plugins/tests/test_plugin_dialog.py
force_wfmanager/ui/tests/test_custom_ui_plugin.py

This PR implements minor changes that are required to accompany refactoring of `force-bdss`, performed in force-h2020/force-bdss/pull/220. Specifically, the relocation of all Envisage plugins to the `force_bdss.core_plugins` module
It should not be merged before force-h2020/force-bdss/pull/220

WfManager Updates to accompany Refactor of BDSS Application

---

force_wfmanager/utils/variable_names_registry.py

A broken reference to `factory.plugin.id` has been removed from the `VariableNamesRegistry.update_available_variables_stacks` method. This was previously missed in #331 as it only occurred during an exception that was not covered in the test suite.
It is also not advisable for a change handler to raise an exception, so creating a unit test for this case is not as beneficial as refactoring the code (taken care of in #329)

FIX: Removed broken factory.plugin.id reference

---

force_wfmanager/server/event_deserializer.py
force_wfmanager/server/event_serializer.py
force_wfmanager/server/tests/test_event_deserializer.py
force_wfmanager/server/tests/test_event_serializer.py
force_wfmanager/server/tests/test_zmq_server.py

The ZMQ server method for serializing `BaseDriverEvent` instances as JSON files did not contain enough information for full deserialization, leading to a fragile implementation of the ZMQ server deserialization method.
Specifically, the module location of `BaseDriverEvent` classes and subclasses was determined by the deserialization method, and set to `force_bdss.api`. Therefore the ZMQ server was not able to pass any subclasses of `BaseDriverEvent` that may have been contributed by additional plugins and therefore not exist in the core `force-bdss` module.
In order to provide a more robust implementation, we include a `module` reference in the serialized JSON, as well as a way to import the `BaseDriverEvent` class from this reference using the `importlib` library in the deserialize …

FIX: ZMQ Server event serialization / deserialization

---

.travis.yml

- EDM Linux installer targets RH6
- EDM version bumped to 2.1.0 (`edm_cli` installer used for Linux)

MAINT: Updates to Travis CI

---

.travis.yml
force_wfmanager/ui/setup/mco/tests/test_base_mco_options_view.py
force_wfmanager/ui/setup/mco/tests/test_kpi_specification_view.py
force_wfmanager/ui/setup/mco/tests/test_mco_parameter_view.py
force_wfmanager/ui/setup/mco/tests/test_mco_view.py
force_wfmanager/ui/setup/process/tests/test_data_source_view.py
force_wfmanager/ui/setup/tests/test_setup_pane.py
force_wfmanager/ui/setup/tests/test_workflow_tree.py
force_wfmanager/ui/setup/tests/test_workflow_view.py
force_wfmanager/ui/setup/tests/wfmanager_base_test_case.py
force_wfmanager/ui/setup/workflow_tree.py
force_wfmanager/ui/setup/workflow_view.py
force_wfmanager/utils/tests/test_variable_names_registry.py
force_wfmanager/utils/variable_names_registry.py

This PR approaches the BDSS issue [#246](https://github.com/force-h2020/force-bdss/issues/246) and implements the required API changes.
This PR requires the [BDSS PR](https://github.com/force-h2020/force-bdss/pull/257) to be accepted first.
We rename the `Workflow.mco` usage to `Workflow.mco_model` whenever necessary. This is a recent change in BDSS (see [this PR](https://github.com/force-h2020/force-bdss/pull/257))
We remove the redundant `Workflow_view.set_mco` method: now the BDSS changes allow safe attribute assignment directly.
Some general code formatting changes are also present.

Workflow mco_model attribute name change

---

README.rst

The README build status introduced in #337 used travis-ci.org as a host, rather than travis-ci.com.
Force repositories have been migrated to travis-ci.com over a year ago, and so the current status is not referencing the latest commit.

FIX: Build status reference in README

---

ci/__main__.py

This PR closes #292
Bumping to `chaco==4.8.0-1` removes library code that raised DeprecationWarnings for `set` and `get` methods.
Bumping to `pyface==6.1.2-1` also removes pinned commit introduced in #276, since bug fix is now included in version 6.1.2. By doing so, we also are required to update `traitsui`

MAINT: Update chaco and pyface dependencies

---

force_wfmanager/server/tests/test_event_deserializer.py
force_wfmanager/tests/test_wfmanager_setup_task.py

This PR fixes the failing build of `master` branch.
Removed the `weights` attribute references from the `MCOProgressEvent` tests.

FIX: tests fix, removed the weights attribute

---

force_wfmanager/ui/review/plot.py
force_wfmanager/ui/review/results_table.py
force_wfmanager/ui/review/tests/test_plot.py

This PR refactors the `BasePlot` class. The aim was to make implementation of the axis and data updates more transparent, and eliminate multiple calls of traits listeners all over the code.
We also refactor the way the view is generated, which allows better and easier customization.
- Added `default_traits_view` method. It generates the `VGroup` as before, but the first entry of the group is not provided by the `self.axis_hgroup` attribute. If we want to create a different view for the axis choice panel, we can implement a custom `self.axis_hgroup`.  For example, the `BasePlot` has:
```
def _axis_hgroup_default(self):
return HGroup(
Item("x", editor=EnumEditor(name="displayable_value_names")),
Item("y", editor=EnumEditor(name="displayable_value_names")),
)
```
The `Plot` class overwrites …

MAINT: Plot axis view

---

CHANGES.rst
ci/__main__.py

This PR bumps Pyface and TraitsUI to latest versions available on EDM, in order to support https://github.com/force-h2020/force-bdss/pull/289
- `pyface` 6.1.2-1 --> 6.1.2-5
- `traitsui` 6.1.3-2 --> 6.1.3-5

MAINT: Updated dependencies for version 0.4.0

---

force_wfmanager/io/project_io.py
force_wfmanager/model/analysis_model.py
force_wfmanager/tests/test_wfmanager_setup_task.py
force_wfmanager/tests/test_wfmanager_tasks.py
force_wfmanager/wfmanager_review_task.py
force_wfmanager/wfmanager_setup_task.py

This PR approaches #303 
The `force_wfmanager` can executed with a Workflow or Project File. When a Project File is loaded, the user should not be able to `"Save"` the workflow file from the setup pane, as it would overwrite the Project file and therefore the analysis model data will be erased. Since the Workflow and Project files have the same file format (and share the .json extension), it is not possible to guess the file content without reading the file.
In the `setup_pane` environment, we check whether the loaded file contains the `analysis_model` data, and if it does, the `"Save"` button activates the `"Save as"` function.
In the `review_pane` environment, if the user loads a Workflow file instead of a Project file, the WorkflowManager can now process the workflow file and assigns …

FIX: Open project file

---

force_wfmanager/wfmanager_setup_task.py

This PR adds a missing fix that was supposed to be a part of #354 
The `self.computation_running = True` flag should be set on the `WfManagerSetupTask` only after the `MCOStartEvent` has been received, not when the `force-bdss` execution has been submitted.

DEV: computation_running set after MCOStartEvent received

---

.travis.yml
force_wfmanager/notifications/tests/test_ui_notification.py
force_wfmanager/notifications/ui_notification.py

This PR closes #361 
We introduced a small `UIEventMixin` class in [#290](https://github.com/force-h2020/force-bdss/pull/290) that indicates that this particular event type should be parsed and sent to the WorkflowManager.
Here we add the actual logic to filter this event type before delivering via the `UINotification.deliver`
- Added a `if isinstance(event, UIEventMixin)` check in the `UIEventMixin.deliver` method. Only events that are subclasses of the `UIEventMixin` will be dumped and sent to the ZMQ server.

DEV: Delivering UIEventMixin events

---

.travis.yml
force_wfmanager/tests/probe_classes.py
force_wfmanager/ui/setup/mco/base_mco_options_model_view.py
force_wfmanager/ui/setup/mco/mco_parameter_model_view.py
force_wfmanager/ui/setup/mco/tests/test_base_mco_options_model_view.py
force_wfmanager/ui/setup/process/tests/test_data_source_view.py
force_wfmanager/ui/setup/tests/test_new_entity_creator.py
force_wfmanager/ui/tests/test_ui_utils.py

This PR effectively carries the same verification functionalities in #296 to `BaseMCOParamter` and `KPISpecification` subclasses.
It also removes some probe classes that have been ported over to `force_bdss` in https://github.com/force-h2020/force-bdss/pull/295, and so requires these updates in order for the unit tests to pass.

ENH: Verification on any BaseMCOParameter or KPISpecification trait

---

force_wfmanager/tests/test_wfmanager_setup_task.py
force_wfmanager/ui/setup/setup_pane.py
force_wfmanager/ui/setup/side_pane.py
force_wfmanager/ui/setup/tests/test_setup_pane.py
force_wfmanager/wfmanager_setup_task.py

This PR closes #358 
It adds a new attribute `ui_enabled` to the `SetupPane` class, which controls whether the UI features are enabled or not during a BDSS run. By doing so we are also able to remove the same control on the `SidePane` tree view, so that it remains selectable during run time and allows the user to look at the `Workflow` state without being able to edit anything.
The `SidePane.ui_enabled` attribute is retained, as it is involved in the logic defining the status of the run buttons.
- The view objects of the `SetupPane` are a bit convoluted, and we are not able to simply set the enable status of a single object. It would be great if we could refactor the view into something that has a single `Group`, so that `visible` or `enabled` states could be easily set for the entire …

ENH: Control enabling of SetupPane UI features during BDSS run

---

force_wfmanager/ui/review/plot.py
force_wfmanager/ui/review/tests/test_plot.py

Closes #369. Length of set is calculated before if-else ladder, as otherwise set would have to be called twice on a long list with a set size of 1.

switch if length of data set rather than data

---

force_wfmanager/tests/test_wfmanager.py
force_wfmanager/wfmanager.py
force_wfmanager/wfmanager_global_task.py
force_wfmanager/wfmanager_review_task.py
force_wfmanager/wfmanager_setup_task.py

#374, #377 
Implements the proposed change in #377  to remove the `File --> Exit` drop down item, and any routines in the `Task` level that exit the application.
Doing so reduces the current menu bar features from:
to: 
Although this reduces UI features, It removes code that was not appropriate for the application level it was being used.
Additionally, if the application is exited in any remaining way, a pop up window will still appear, prompting the user to save the workflow.
- Removes `WfManagerSetupTask.exit` and `WfManagerReviewTask.exit` methods
- References to `task.name` now use `task.id` in methods that swap the display between `Task` objects

CLN: Tidy up Application exit routines

---

doc/source/conf.py
force_wfmanager/ui/setup/tests/test_workflow_tree.py
force_wfmanager/ui/setup/workflow_tree.py

When the user selects a new MCO, the parameters and kpis are wiped and then the user has to
set them again. (#381). This makes a small change to `WorkflowTree.new_mco()`, so that the new MCO's parameters and kpis are set to those of the old MCO.
#381
This makes a small change to `WorkflowTree.new_mco()`, that sets the new MCO's parameters and kpis to those of the old MCO. The kpis can just be copied as they are self-contained. Each parameter refers to the MCOModel and plugin (via their factories) and these are changed appropriately.

Revert params

---

.travis.yml
ci/__main__.py

Bumps TraitsUI (plus Pyface, Chaco) version to support Traits 6.1.0
Should NOT be merged before https://github.com/force-h2020/force-bdss/pull/356
Envisage dependency now a `4.9.2-3`
- Exploring new features in traits 6.1.0 (`observe` functionality)
- Dependency bump: `pyface==7.0.0-3`,  `traitsui==7.0.0-2`, `chaco==4.8.0-4`

MAINT: Update to Pyface and TraitsUI 

---

force_wfmanager/ui/setup/new_entity_creator.py

Includes MathJax support in the `NewEntityCreator` view
Closes #399 
Adds a script that installs MathJax to the HTML code header when rendering factor descriptions in the new entity creation
From what I can tell TraitsUI `HTMLEditor` only supports MathJax v 2.7.1
- Includes support for MathJax formatted text in New Entity Creator

ENH: Include MathJax in new entity creator HTML header

---

force_wfmanager/ui/setup/setup_pane.py
force_wfmanager/ui/setup/workflow_tree.py

Provides a workaround to #382 
Closes #382 
Includes scrollable options on setup and side pane views so that they do not automatically resize on selection of objects.
Also tested on Simphony-Remote - prevents the screen from expanding outside the browser display

ENH: include scrollable workaround to prevent UI from resizing

---

force_wfmanager/tests/test_wfmanager_review_task.py
force_wfmanager/ui/review/curve_scatter_plot.py
force_wfmanager/ui/review/data_view_pane.py
force_wfmanager/ui/review/plot.py
force_wfmanager/ui/review/tests/test_curve_scatter_plot.py
force_wfmanager/ui/review/tests/test_data_view_pane.py
force_wfmanager/ui/ui_utils.py

Adds a new `BaseDataView` to the default plot types available, which is a scatter plot that displays an (optional) fitted curve through the 2D data points
Includes `CurveScatterPlot` class, which is selectable by default in the UI.
Some refactoring is also performed to enable easy inheritance between `Plot` and `CurveScatterPlot` classes.
At the moment a simple interpolation is performed between data points, which does not work very well for noisy data. We should consider using a more complex fitting, such as BSplines, in the future
Additionally, refactoring the `BasePlot` classes to not inherit, but extend features of the scatter plot would be a better architecture. Some mixin system would therefore be desirable.
- We may want to only include one plot by default, since the curve display …

ENH: Add CurveScatterPlot as a default plot type

---

force_wfmanager/model/analysis_model.py
force_wfmanager/model/tests/test_analysis_model.py
force_wfmanager/tests/dummy_classes/dummy_events.py
force_wfmanager/tests/test_wfmanager_setup_task.py
force_wfmanager/tests/test_wfmanager_tasks.py
force_wfmanager/wfmanager_setup_task.py

Allows data sources to report metadata values to the `AnalaysisModel` for each MCO step. These are then accessible via the `step_metadata` attribute, which contains a list of dictionaries.
Concerns https://github.com/force-h2020/force-bdss/issues/200
Each element of the workflow has the ability to report data to the WfManager via `BaseDriverEvents` that inherit from the `UIEventMixin` classs. However, the `AnalaysisModel` has not been able to store data that is reported during an evaluation of the Workflow, only that delieverd by a `MCOProgressEvent`, containing the parameters and KPIs.
Provides the `AnalysisModel.step_metadata` dictionary trait to store metadata for each Workflow run and methods to ensure this is correctly populated during the calculation.
`BaseDataView` classes can now …

DEV: Support metadata being reported to the AnalaysisModel

---

force_wfmanager/ui/review/scatter_plot.py
force_wfmanager/ui/review/tests/test_scatter_plot.py

An exception was being thrown when calling `ScatterPlot(use_color_plot=True)`, which was caused by a trait listener that references `self._plot_data` being called before the init routine had assigned this trait.
Including the `post_init=True` metadata on the problem listener (`ScatterPlot.change_plot_style`) resolves this issue. 
A unit test is also introduced to assert that the constructor can handle initializing `ScatterPlot(use_color_plot=True)`
- Bugfix for ScatterPlot initialising class as a color plot

FIX: ScatterPlot not initializing with use_color_plot=True
