force-h2020/force-wfmanager

force_wfmanager/left_side_pane/workflow_settings.py, force_wfmanager/wfmanager_plugin.py, force_wfmanager/wfmanager_task.py
Adds support for the new concept of bundles in the force BDSS.
=> Add bundles support

force_wfmanager/left_side_pane/workflow_settings.py
Use of the list editor for displaying the available elements (MCOs, data sources...).
=> Use list editor for the available plugins

doc/source/api/force_wfmanager.central_pane.rst, doc/source/api/force_wfmanager.left_side_pane.rst, doc/source/api/force_wfmanager.rst, doc/source/conf.py
Incorrect path specification was not importing the module
=> Fix importing path of module for documentation

setup.py
Tries to rebuild the coverage for master branch and verify if codecov works.
=> Rebuilding testing coverage for master

.travis.yml, force_wfmanager/central_pane/central_pane.py, requirements/requirements.txt
Fix doc build by adding missing requirement and cleaning import, and fix coverage report by changing directory during travis build
=> Fix the travis build and coverage

force_wfmanager/left_side_pane/new_entity_modal.py, force_wfmanager/left_side_pane/workflow_model_view.py, force_wfmanager/left_side_pane/workflow_settings.py, force_wfmanager/wfmanager_plugin.py, test/test_new_entity_modal.py, test/test_workflow_settings.py
Matches the changes in the FORCE BDSS.
=> Rename MultiCriteriaOptimizer to MCO

test/test_bundle_name.py, test/test_new_entity_modal.py, test/test_workflow_settings.py
The bundles now takes the plugin as argument when creating an instance
=> Fix tests according to force_bdss changes

force_wfmanager/left_side_pane/workflow_model_view.py, force_wfmanager/left_side_pane/workflow_settings.py, force_wfmanager/wfmanager_task.py
=> Use List(Instance()) instead of List()

force_wfmanager/left_side_pane/new_entity_modal.py
=> Fix issue when double clicking in the list of bundles

force_wfmanager/left_side_pane/workflow_model_view.py, force_wfmanager/left_side_pane/workflow_settings.py, force_wfmanager/wfmanager_task.py
=> Add allow_none=False to workflow objects

force_wfmanager/left_side_pane/workflow_settings.py
makes the orientation vertical so that the model values end up to the bottom of the column
=> Change tree editor orientation

force_wfmanager/left_side_pane/data_source_model_view.py, force_wfmanager/left_side_pane/kpi_calculator_model_view.py, force_wfmanager/left_side_pane/mco_model_view.py, force_wfmanager/left_side_pane/mco_parameter_model_view.py, force_wfmanager/left_side_pane/view_utils.py, force_wfmanager/left_side_pane/workflow_model_view.py, force_wfmanager/left_side_pane/workflow_settings.py, test/test_data_source_model_view.py, test/test_kpi_calculator_model_view.py, test/test_mco_model_view.py, test/test_mco_parameter_model_view.py, test/test_workflow_model_view.py, test/test_workflow_settings.py
Create ModelView classes for the MCO parameters, data sources and KPI calculators.
This will help for the integration of the slots, because then the slots will be part of the DataSourceModelView and the KPICalculatorModelView.
=> Create model views

force_wfmanager/left_side_pane/workflow_settings.py
Changed the name of the edit menu action from "Edit" to "Edit..." so that it is clear that it opens a dialog.
Changed the behavior of the edit dialog so that it updates the changes on the model only when submitting the dialog.
=> Change Edit menu action to provide modal dialog.

force_wfmanager/wfmanager_plugin.py, test/test_wfmanager_plugin.py
Improves coverage by checking create_task.
=> Add tests for improving coverage of _create_task

setup.py
Modified cython and numpy requirements that were incorrectly stated.
=> Fix dependencies version so that it fits with edm_requirements

setup.py
=> Renamed program to use underscore

force_wfmanager/tests/test_wfmanager_task.py, force_wfmanager/wfmanager_task.py
=> Renamed "Load" action into "Open"

force_wfmanager/left_side_pane/side_pane.py
=> Removes the possibility to move the SidePane in the GUI

force_wfmanager/left_side_pane/new_entity_modal.py, force_wfmanager/left_side_pane/side_pane.py, force_wfmanager/left_side_pane/tests/test_new_entity_modal.py, force_wfmanager/left_side_pane/tests/test_workflow_settings.py, force_wfmanager/left_side_pane/workflow_settings.py
Rename `available_*_factories` into `*_factories`
Fixes #71
=> Rename WorkflowSettings attributes

codecov.yml
Allow for less strict codecov coverage.
=> Added codecov configuration

force_wfmanager/left_side_pane/evaluator_model_view.py
=> Use Identifier trait instead of Str for slot names

force_wfmanager/tests/test_wfmanager_task.py, force_wfmanager/wfmanager_task.py
Adds an exit action in the menu bar
Fixes #80
=> Add exit action in the menu bar

force_wfmanager/run.py
Adds basic logging setup to have a logger printout.
=> Added basic logging setup

setup.py
Dependency was missing from the setup
=> Added force_bdss dependency on setup.py

force_wfmanager/central_pane/tests/test_analysis_model.py, force_wfmanager/central_pane/tests/test_central_pane.py, force_wfmanager/central_pane/tests/test_plot.py, force_wfmanager/central_pane/tests/test_result_table.py, force_wfmanager/left_side_pane/tests/test_evaluator_model_view.py, force_wfmanager/left_side_pane/tests/test_factory_name.py, force_wfmanager/left_side_pane/tests/test_mco_model_view.py, force_wfmanager/left_side_pane/tests/test_new_entity_modal.py, force_wfmanager/tests/test_run.py, force_wfmanager/tests/test_wfmanager.py, force_wfmanager/tests/test_wfmanager_plugin.py
=> Rename ClassTest names to TestClass

doc/source/api/force_wfmanager.central_pane.rst, doc/source/api/force_wfmanager.central_pane.tests.rst, doc/source/api/force_wfmanager.left_side_pane.rst, doc/source/api/force_wfmanager.left_side_pane.tests.rst, doc/source/api/force_wfmanager.plugins.rst, doc/source/api/force_wfmanager.plugins.ui_notification.rst, doc/source/api/force_wfmanager.plugins.ui_notification.tests.rst, doc/source/api/force_wfmanager.rst, doc/source/api/force_wfmanager.server.rst, doc/source/api/force_wfmanager.server.tests.rst, doc/source/api/force_wfmanager.tests.rst, doc/source/introduction.rst
Updated docs to the most recent developments (UI Hooks)
=> Update the documentation

force_wfmanager/plugins/ui_notification/tests/test_ui_notification_hooks_factory.py, force_wfmanager/plugins/ui_notification/tests/test_ui_notification_hooks_manager.py, force_wfmanager/plugins/ui_notification/tests/test_ui_notification_plugin.py, force_wfmanager/plugins/ui_notification/ui_notification_hooks_factory.py, force_wfmanager/plugins/ui_notification/ui_notification_hooks_manager.py, force_wfmanager/plugins/ui_notification/ui_notification_plugin.py, force_wfmanager/server/zmq_server_config.py, force_wfmanager/tests/probe_plugin_classes.py, force_wfmanager/tests/test_wfmanager_task.py, force_wfmanager/wfmanager_task.py
Sets up the UI notification during execution
=> Automatic setup of ui notification

force_wfmanager/tests/test_wfmanager_task.py, force_wfmanager/wfmanager_task.py
Add "Help" menu with the "About WorkflowManager..." action which displays license informations
=> Add "Help" menu

force_wfmanager/tests/test_wfmanager_task.py, force_wfmanager/wfmanager_task.py
Disable the menus actions (save/save as.../load...) when the computation is running
=> Disable the menu actions when the computation is running

force_wfmanager/left_side_pane/tests/test_factory_name.py
Fixes missing ImportError that makes flake8 nervous
=> Fixed missing ImportError

force_wfmanager/left_side_pane/new_entity_modal.py, force_wfmanager/left_side_pane/notification_listener_model_view.py, force_wfmanager/left_side_pane/tests/test_notification_listener_model_view.py, force_wfmanager/left_side_pane/tests/test_workflow_model_view.py, force_wfmanager/left_side_pane/tests/test_workflow_tree.py, force_wfmanager/left_side_pane/workflow_model_view.py, force_wfmanager/left_side_pane/workflow_tree.py
Introduces a UI to configure the notification listeners.
=> Introduced notification listener UI

doc/source/introduction.rst, force_wfmanager/left_side_pane/tests/test_data_source_model_view.py, force_wfmanager/left_side_pane/tests/test_factory_name.py, force_wfmanager/left_side_pane/tests/test_mco_parameter_model_view.py, force_wfmanager/left_side_pane/tests/test_new_entity_modal.py, force_wfmanager/left_side_pane/tests/test_notification_listener_model_view.py, force_wfmanager/left_side_pane/tests/test_variable_names_registry.py, force_wfmanager/left_side_pane/tests/test_workflow_model_view.py, force_wfmanager/plugins/ui_notification/tests/test_ui_notification_factory.py, force_wfmanager/plugins/ui_notification/tests/test_ui_notification_hooks_factory.py, force_wfmanager/plugins/ui_notification/tests/test_ui_notification_hooks_manager.py, force_wfmanager/plugins/ui_notification/ui_notification_factory.py, force_wfmanager/plugins/ui_notification/ui_notification_hooks_factory.py, force_wfmanager/plugins/ui_notification/ui_notification_hooks_manager.py, force_wfmanager/plugins/ui_notification/ui_notification_plugin.py
Uses new API to define the plugin information.
=> Updated against new API

force_wfmanager/left_side_pane/data_source_model_view.py
=> Fixes initialization order of Input and Output slot rows

force_wfmanager/left_side_pane/data_source_model_view.py, force_wfmanager/left_side_pane/kpi_specification_model_view.py, force_wfmanager/left_side_pane/mco_model_view.py, force_wfmanager/left_side_pane/tests/test_kpi_specification_model_view.py, force_wfmanager/left_side_pane/tests/test_mco_model_view.py, force_wfmanager/left_side_pane/tests/test_variable_names_registry.py, force_wfmanager/left_side_pane/tests/test_workflow_tree.py, force_wfmanager/left_side_pane/variable_names_registry.py, force_wfmanager/left_side_pane/workflow_model_view.py, force_wfmanager/left_side_pane/workflow_tree.py
Adapts the code to the new KPI design in the force-bdss.
Fixes #155
=> Sync against KPI change in force-bdss

force_wfmanager/run.py, force_wfmanager/tests/test_click_run.py, force_wfmanager/tests/test_run.py, setup.py
Relates to issue #151 and will be used for tests of new cli module in issue #119
=> Added --version command line arg

.travis.yml, requirements/edm_requirements.txt, requirements/requirements.txt
=> Update dependencies to fix traitsui issue

force_wfmanager/central_pane/central_pane.py
=> 165 result plot tabs

force_wfmanager/left_side_pane/data_source_model_view.py, force_wfmanager/left_side_pane/kpi_specification_model_view.py, force_wfmanager/left_side_pane/tests/test_kpi_specification_model_view.py
Makes workflow tree display track kpi names
=> 160 update kpi mv label

force_wfmanager/central_pane/tests/test_plot.py
=> Suppress DeprecationWarning from Chaco in tests

force_wfmanager/gui/run.py, force_wfmanager/left_side_pane/side_pane.py, force_wfmanager/tests/test_wfmanager_plugin.py, force_wfmanager/wfmanager_plugin.py, force_wfmanager/wfmanager_task.py
This works fine at present, but it would be good to know if there's a better way to pass through arguments. At the minute it always passes a filename argument, which is either None or a filepath string. It's not too bad for just one input, but if there are going to be a lot of command line options it may need restructuring.
Fixes #147
=> Open file from command line

force_wfmanager/gui/run.py, force_wfmanager/left_side_pane/data_source_model_view.py, force_wfmanager/left_side_pane/execution_layer_model_view.py, force_wfmanager/left_side_pane/kpi_specification_model_view.py, force_wfmanager/left_side_pane/notification_listener_model_view.py, force_wfmanager/left_side_pane/side_pane.py, force_wfmanager/left_side_pane/tests/test_data_source_model_view.py, force_wfmanager/left_side_pane/tests/test_kpi_specification_model_view.py, force_wfmanager/left_side_pane/tests/test_mco_model_view.py, force_wfmanager/left_side_pane/tests/test_variable_names_registry.py, force_wfmanager/left_side_pane/tests/test_workflow_model_view.py, force_wfmanager/left_side_pane/tests/test_workflow_tree.py, force_wfmanager/left_side_pane/variable_names_registry.py, force_wfmanager/left_side_pane/workflow_model_view.py, force_wfmanager/left_side_pane/workflow_tree.py, force_wfmanager/plugins/ui_notification/tests/test_ui_notification_hooks_manager.py, force_wfmanager/tests/test_wfmanager_task.py, force_wfmanager/wfmanager_task.py
Needs https://github.com/force-h2020/force-bdss/pull/159 before it will build. Addresses issue #156.
=> Imports from force_bdss set to use api

force_wfmanager/left_side_pane/new_entity_modal.py
Relies on https://github.com/force-h2020/force-bdss/pull/169, fixes #198
=> Using Basefactory in NewModalDialog

force_wfmanager/left_side_pane/new_entity_modal.py, force_wfmanager/left_side_pane/tests/test_new_entity_modal.py, force_wfmanager/left_side_pane/tests/test_workflow_tree.py, force_wfmanager/left_side_pane/view_utils.py, force_wfmanager/left_side_pane/workflow_tree.py
Made the windows nicer by adding decoration boxes around them
Fixes #183
=> Added windows decorations to the model visualisation

.travis.yml, ci/__main__.py
Codecov was not running anymore. This PR reenables it.
=> Reenable codecov in the build

ci/__main__.py
Run verbose tests so that we can get more information about potential noisy tests.
=> Do verbose tests

force_wfmanager/left_side_pane/workflow_tree.py
So this feels way too simple, but I don't think we lose anything by throwing away the modelview things on load. It seems to work but I'm not 100% that I'm not missing something further down the line.
Fixes #209
=> File Loading Fix

force_wfmanager/plugins/ui_notification/tests/test_ui_notification_plugin.py, force_wfmanager/plugins/ui_notification/ui_notification_plugin.py
Requires support from the BDSS. see https://github.com/force-h2020/force-bdss/pull/174
=> Adds name version and description to plugin

force_wfmanager/wfmanager.py
Reverts force-h2020/force-wfmanager#214
=> Revert "Title bar close bugfix"

CHANGES.rst, setup.py
=> Release 0.2.0

force_wfmanager/gui/tests/test_click_run.py, force_wfmanager/left_side_pane/data_source_model_view.py, force_wfmanager/left_side_pane/execution_layer_model_view.py, force_wfmanager/left_side_pane/kpi_specification_model_view.py, force_wfmanager/left_side_pane/mco_model_view.py, force_wfmanager/left_side_pane/mco_parameter_model_view.py, force_wfmanager/left_side_pane/new_entity_modal.py, force_wfmanager/left_side_pane/notification_listener_model_view.py, force_wfmanager/left_side_pane/tests/test_data_source_model_view.py, force_wfmanager/left_side_pane/tests/test_new_entity_modal.py, force_wfmanager/left_side_pane/tests/test_workflow_tree.py, force_wfmanager/left_side_pane/workflow_model_view.py, force_wfmanager/left_side_pane/workflow_tree.py, force_wfmanager/plugin_dialog.py, force_wfmanager/plugins/ui_notification/tests/test_ui_notification.py, force_wfmanager/plugins/ui_notification/tests/test_ui_notification_hooks_manager.py, force_wfmanager/plugins/ui_notification/tests/test_ui_notification_plugin.py, force_wfmanager/server/tests/test_zmq_server.py, force_wfmanager/tests/test_plugin_dialog.py, force_wfmanager/tests/test_run.py, force_wfmanager/tests/test_wfmanager_plugin.py, force_wfmanager/tests/test_wfmanager_task.py, force_wfmanager/wfmanager_task.py
Doing unicode check so that we can switch to python 3 completely.
=> Unicode check and porting to py3

force_wfmanager/wfmanager.py
=> Fix for incorrect envisage function args

CHANGES.rst, setup.py
Release commit for Workflow Manager 0.3.0
=> 0.3.0 release

force_wfmanager/central_pane/tests/test_setup_pane.py, force_wfmanager/gui/run.py, force_wfmanager/left_side_pane/tests/test_workflow_info.py, force_wfmanager/left_side_pane/tests/test_workflow_tree.py, force_wfmanager/left_side_pane/tree_pane.py, force_wfmanager/left_side_pane/workflow_tree.py, force_wfmanager/plugins/ui_notification/tests/test_ui_notification_hooks_manager.py, force_wfmanager/tests/test_wfmanager.py, force_wfmanager/tests/test_wfmanager_tasks.py, force_wfmanager/wfmanager_plugin.py, force_wfmanager/wfmanager_setup_task.py, setup.py
Awaiting merging of force-h2020/force-bdss#208. This should further disentangle the wfmanager and envisage.
=> Update to new BDSS FactoryRegistry service instead of plugin

force_wfmanager/left_side_pane/kpi_specification_model_view.py
Pre-requisite pull requests = https://github.com/force-h2020/force-bdss/pull/215
=> UI support for KPI scale_factors

force_wfmanager/left_side_pane/kpi_specification_model_view.py
Pre-requisite PRs = https://github.com/force-h2020/force-bdss/pull/216
=> UI support for automated scaling of KPIs in MCO

force_wfmanager/left_side_pane/workflow_info.py, force_wfmanager/left_side_pane/workflow_tree.py, force_wfmanager/server/tests/test_zmq_server.py, force_wfmanager/server/zmq_server.py
I'm upgrading Flake8 in `force-bdss`, and that will require these updates here.
=> Fixes to comply to Flake8 3.7.7

.travis.yml, force_wfmanager/notifications/tests/test_ui_notification_hooks_factory.py, force_wfmanager/notifications/ui_notification_hooks_manager.py, force_wfmanager/ui/setup/new_entity_creator.py, force_wfmanager/ui/setup/tests/test_new_entity_creator.py
This PR implements updates required by the refactoring of `force_bdss` in force-h2020/force-bdss/pull/232
- `NewEntityCreator` class `_plugins_root_default` method refactored
- All `factory.plugin.id` references updated to `factory.plugin_id`
- All `factory.plugin.name` references updated to `factory.plugin_name`
**Note:** this branch is pinned to `force-bdss/enh/refactor-factory-plugin` and should not be merged before force-h2020/force-bdss/pull/232 is closed
=> Updates to BDSS BaseFactory Refactor

README.rst
This PR provides a minor update of the FORCE WfManager documentation, following the style of https://github.com/force-h2020/force-bdss/pull/259
=> DOC: Minor update to Documentation

force_wfmanager/notifications/ui_notification_model.py, force_wfmanager/plugins/plugin_dialog.py, force_wfmanager/plugins/wfmanager_plugin.py, force_wfmanager/ui/contributed_ui/contributed_ui.py, force_wfmanager/ui/contributed_ui/i_contributed_ui.py, force_wfmanager/ui/contributed_ui/ui_select_modal.py, force_wfmanager/ui/review/data_view_pane.py, force_wfmanager/ui/review/plot.py, force_wfmanager/ui/setup/communicator/notification_listener_view.py, force_wfmanager/ui/setup/mco/base_mco_options_model_view.py, force_wfmanager/ui/setup/mco/base_mco_options_view.py, force_wfmanager/ui/setup/mco/kpi_specification_model_view.py, force_wfmanager/ui/setup/mco/kpi_specification_view.py, force_wfmanager/ui/setup/mco/mco_parameter_model_view.py, force_wfmanager/ui/setup/mco/mco_parameter_view.py, force_wfmanager/ui/setup/mco/mco_view.py, force_wfmanager/ui/setup/new_entity_creator.py, force_wfmanager/ui/setup/process/data_source_view.py, force_wfmanager/ui/setup/process/execution_layer_view.py, force_wfmanager/ui/setup/process/process_view.py, force_wfmanager/ui/setup/setup_pane.py, force_wfmanager/ui/setup/system_state.py, force_wfmanager/ui/setup/workflow_info.py, force_wfmanager/ui/setup/workflow_tree.py, force_wfmanager/ui/setup/workflow_view.py, force_wfmanager/utils/local_traits.py, force_wfmanager/wfmanager_setup_task.py
=> CLN: Replace Unicode traits with Str

CHANGES.rst, setup.py
This PR bumps the `master` branch version of Force WfManager to 0.5.0dev0
=> DEV: Bumped WfManager to Version 0.5.0dev0

.github/pull_request_template.md
https://github.com/force-h2020/force-bdss/pull/337
Provides a PR template, equivalent to that of the `force_bdss`
- New `.github/pull_request_template.md`
=> DOC: Provide PR template

.travis.yml, force_wfmanager/ui/setup/mco/kpi_specification_model_view.py
Updates the KPI model views with additional options
Should not be merged before the relevant BDSS PR is
https://github.com/force-h2020/force-bdss/pull/353
- Updated the default traits view for `KPISpecificationModelView`
=> ENH: KPI ModelView with additional options

ci/__main__.py
Updates Traits, TraitsUI and Pyface to latest versions available on EDM
Closes #397 
```
traits:    6.1.1-0 --> 6.1.1-1
traitsui:  7.0.0-2 --> 7.0.1-2
pyface:    7.0.0-3 --> 7.0.1-2
```
- Updates Traits to 6.1.1-1, TraitsUI to 7.0.1-2 and Pyface to 7.0.1-2
=> MAINT: Updates to ETS dependencies

CHANGES.rst, setup.py
Updates `force_wfmanager` package version to 0.6.0.dev
- Version in `setup.py` now 0.6.0.dev
=> MAINT: Bump to development version 0.6.0.dev
